/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.12.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * There are many Progressions in Destiny (think Character Level, or Reputation). These are the various \"Scopes\" of Progressions, which affect many things: * Where/if they are stored * How they are calculated * Where they can be used in other game logic
 */
export type DestinyDestinyProgressionScope = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

export const DestinyDestinyProgressionScope = {
  NUMBER_0: 0 as DestinyDestinyProgressionScope,
  NUMBER_1: 1 as DestinyDestinyProgressionScope,
  NUMBER_2: 2 as DestinyDestinyProgressionScope,
  NUMBER_3: 3 as DestinyDestinyProgressionScope,
  NUMBER_4: 4 as DestinyDestinyProgressionScope,
  NUMBER_5: 5 as DestinyDestinyProgressionScope,
  NUMBER_6: 6 as DestinyDestinyProgressionScope,
  NUMBER_7: 7 as DestinyDestinyProgressionScope,
  NUMBER_8: 8 as DestinyDestinyProgressionScope
};
