/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.12.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * As you run into items that need to be classified for Milestone purposes in ways that we cannot infer via direct data, add a new classification here and use a string constant to represent it in the local item config file.  NOTE: This is not all of the item types available, and some of these are holdovers from Destiny 1 that may or may not still exist.
 */
export type DestinySpecialItemType = 0 | 1 | 8 | 9 | 23 | 24 | 25 | 27 | 29;

export const DestinySpecialItemType = {
  NUMBER_0: 0 as DestinySpecialItemType,
  NUMBER_1: 1 as DestinySpecialItemType,
  NUMBER_8: 8 as DestinySpecialItemType,
  NUMBER_9: 9 as DestinySpecialItemType,
  NUMBER_23: 23 as DestinySpecialItemType,
  NUMBER_24: 24 as DestinySpecialItemType,
  NUMBER_25: 25 as DestinySpecialItemType,
  NUMBER_27: 27 as DestinySpecialItemType,
  NUMBER_29: 29 as DestinySpecialItemType
};
