/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.12.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The possible states of Destiny Profile Records. IMPORTANT: Any given item can theoretically have many of these states simultaneously: as a result, this was altered to be a flags enumeration/bitmask for v3.2.0.
 */
export type DestinyDestinyVendorItemState =
  | 0
  | 1
  | 2
  | 4
  | 8
  | 16
  | 32
  | 64
  | 128
  | 256
  | 512
  | 1024
  | 2048
  | 4096
  | 8192
  | 16384
  | 32768
  | 65536;

export const DestinyDestinyVendorItemState = {
  NUMBER_0: 0 as DestinyDestinyVendorItemState,
  NUMBER_1: 1 as DestinyDestinyVendorItemState,
  NUMBER_2: 2 as DestinyDestinyVendorItemState,
  NUMBER_4: 4 as DestinyDestinyVendorItemState,
  NUMBER_8: 8 as DestinyDestinyVendorItemState,
  NUMBER_16: 16 as DestinyDestinyVendorItemState,
  NUMBER_32: 32 as DestinyDestinyVendorItemState,
  NUMBER_64: 64 as DestinyDestinyVendorItemState,
  NUMBER_128: 128 as DestinyDestinyVendorItemState,
  NUMBER_256: 256 as DestinyDestinyVendorItemState,
  NUMBER_512: 512 as DestinyDestinyVendorItemState,
  NUMBER_1024: 1024 as DestinyDestinyVendorItemState,
  NUMBER_2048: 2048 as DestinyDestinyVendorItemState,
  NUMBER_4096: 4096 as DestinyDestinyVendorItemState,
  NUMBER_8192: 8192 as DestinyDestinyVendorItemState,
  NUMBER_16384: 16384 as DestinyDestinyVendorItemState,
  NUMBER_32768: 32768 as DestinyDestinyVendorItemState,
  NUMBER_65536: 65536 as DestinyDestinyVendorItemState
};
