/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.12.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Describes the type of progression that a vendor has.
 */
export type DestinyDestinyVendorProgressionType = 0 | 1;

export const DestinyDestinyVendorProgressionType = {
  NUMBER_0: 0 as DestinyDestinyVendorProgressionType,
  NUMBER_1: 1 as DestinyDestinyVendorProgressionType
};
