/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.12.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * When a Vendor Interaction provides rewards, they\'ll either let you choose one or let you have all of them. This determines which it will be.
 */
export type DestinyDestinyVendorInteractionRewardSelection = 0 | 1 | 2;

export const DestinyDestinyVendorInteractionRewardSelection = {
  NUMBER_0: 0 as DestinyDestinyVendorInteractionRewardSelection,
  NUMBER_1: 1 as DestinyDestinyVendorInteractionRewardSelection,
  NUMBER_2: 2 as DestinyDestinyVendorInteractionRewardSelection
};
