/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.12.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Presentation nodes can be restricted by various requirements. This defines the rules of those requirements, and the message(s) to be shown if these requirements aren\'t met.
 */
export interface DestinyDefinitionsPresentationDestinyPresentationNodeRequirementsBlock {
  /**
   * If this node is not accessible due to Entitlements (for instance, you don\'t own the required game expansion), this is the message to show.
   */
  entitlementUnavailableMessage?: string;
}
