/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.12.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type DestinyTierType = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export const DestinyTierType = {
  NUMBER_0: 0 as DestinyTierType,
  NUMBER_1: 1 as DestinyTierType,
  NUMBER_2: 2 as DestinyTierType,
  NUMBER_3: 3 as DestinyTierType,
  NUMBER_4: 4 as DestinyTierType,
  NUMBER_5: 5 as DestinyTierType,
  NUMBER_6: 6 as DestinyTierType
};
