/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.12.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent } from './dictionaryComponentResponseOfuint32AndDestinyItemPlugComponent';
import { DictionaryComponentResponseOfint32AndDestinyItemPerksComponent } from './dictionaryComponentResponseOfint32AndDestinyItemPerksComponent';
import { DictionaryComponentResponseOfint32AndDestinyItemPlugObjectivesComponent } from './dictionaryComponentResponseOfint32AndDestinyItemPlugObjectivesComponent';
import { DictionaryComponentResponseOfint32AndDestinyItemStatsComponent } from './dictionaryComponentResponseOfint32AndDestinyItemStatsComponent';
import { DictionaryComponentResponseOfint32AndDestinyItemRenderComponent } from './dictionaryComponentResponseOfint32AndDestinyItemRenderComponent';
import { DictionaryComponentResponseOfint32AndDestinyItemTalentGridComponent } from './dictionaryComponentResponseOfint32AndDestinyItemTalentGridComponent';
import { DictionaryComponentResponseOfint32AndDestinyItemObjectivesComponent } from './dictionaryComponentResponseOfint32AndDestinyItemObjectivesComponent';
import { DictionaryComponentResponseOfint32AndDestinyItemInstanceComponent } from './dictionaryComponentResponseOfint32AndDestinyItemInstanceComponent';
import { DictionaryComponentResponseOfint32AndDestinyItemReusablePlugsComponent } from './dictionaryComponentResponseOfint32AndDestinyItemReusablePlugsComponent';
import { DictionaryComponentResponseOfint32AndDestinyItemSocketsComponent } from './dictionaryComponentResponseOfint32AndDestinyItemSocketsComponent';

export interface DestinyItemComponentSetOfint32 {
  instances?: DictionaryComponentResponseOfint32AndDestinyItemInstanceComponent;
  perks?: DictionaryComponentResponseOfint32AndDestinyItemPerksComponent;
  renderData?: DictionaryComponentResponseOfint32AndDestinyItemRenderComponent;
  stats?: DictionaryComponentResponseOfint32AndDestinyItemStatsComponent;
  sockets?: DictionaryComponentResponseOfint32AndDestinyItemSocketsComponent;
  reusablePlugs?: DictionaryComponentResponseOfint32AndDestinyItemReusablePlugsComponent;
  plugObjectives?: DictionaryComponentResponseOfint32AndDestinyItemPlugObjectivesComponent;
  talentGrids?: DictionaryComponentResponseOfint32AndDestinyItemTalentGridComponent;
  plugStates?: DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent;
  objectives?: DictionaryComponentResponseOfint32AndDestinyItemObjectivesComponent;
}
