/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.12.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyDefinitionsCollectiblesDestinyCollectibleAcquisitionBlock } from './destinyDefinitionsCollectiblesDestinyCollectibleAcquisitionBlock';
import { DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition } from './destinyDefinitionsCommonDestinyDisplayPropertiesDefinition';
import { DestinyDefinitionsCollectiblesDestinyCollectibleStateBlock } from './destinyDefinitionsCollectiblesDestinyCollectibleStateBlock';
import { DestinyDefinitionsPresentationDestinyPresentationChildBlock } from './destinyDefinitionsPresentationDestinyPresentationChildBlock';

/**
 * Defines a
 */
export interface DestinyDefinitionsCollectiblesDestinyCollectibleDefinition {
  displayProperties?: DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition;
  /**
   * Indicates whether the state of this Collectible is determined on a per-character or on an account-wide basis.
   */
  scope?: number;
  /**
   * A human readable string for a hint about how to acquire the item.
   */
  sourceString?: string;
  /**
   * This is a hash identifier we are building on the BNet side in an attempt to let people group collectibles by similar sources.  I can\'t promise that it\'s going to be 100% accurate, but if the designers were consistent in assigning the same source strings to items with the same sources, it *ought to* be. No promises though.  This hash also doesn\'t relate to an actual definition, just to note: we\'ve got nothing useful other than the source string for this data.
   */
  sourceHash?: number;
  itemHash?: number;
  acquisitionInfo?: DestinyDefinitionsCollectiblesDestinyCollectibleAcquisitionBlock;
  stateInfo?: DestinyDefinitionsCollectiblesDestinyCollectibleStateBlock;
  presentationInfo?: DestinyDefinitionsPresentationDestinyPresentationChildBlock;
  presentationNodeType?: number;
  traitIds?: Array<string>;
  traitHashes?: Array<number>;
  /**
   * A quick reference to presentation nodes that have this node as a child. Presentation nodes can be parented under multiple parents.
   */
  parentNodeHashes?: Array<number>;
  /**
   * The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to.
   */
  hash?: number;
  /**
   * The index of the entity as it was found in the investment tables.
   */
  index?: number;
  /**
   * If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
   */
  redacted?: boolean;
}
