import { DestinyDefinitionsPresentationDestinyPresentationNodeDefinition } from 'bungie-api-angular';

export interface PresentationNodeDefinition extends DestinyDefinitionsPresentationDestinyPresentationNodeDefinition {}
