import { DestinyDefinitionsPresentationDestinyPresentationNodeDefinition } from 'bungie-api';

export interface PresentationNodeDefinition extends DestinyDefinitionsPresentationDestinyPresentationNodeDefinition {}
