/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = BungieAPI.Client.SwaggerDateConverter;

namespace BungieAPI.Model
{
    /// <summary>
    /// All Sockets have a \&quot;Type\&quot;: a set of common properties that determine when the socket allows Plugs to be inserted, what Categories of Plugs can be inserted, and whether the socket is even visible at all given the current game/character/account state.  See DestinyInventoryItemDefinition for more information about Socketed items and Plugs.
    /// </summary>
    [DataContract]
    public partial class DestinyDefinitionsSocketsDestinySocketTypeDefinition :  IEquatable<DestinyDefinitionsSocketsDestinySocketTypeDefinition>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DestinyDefinitionsSocketsDestinySocketTypeDefinition" /> class.
        /// </summary>
        /// <param name="DisplayProperties">There are fields for this display data, but they appear to be unpopulated as of now. I am not sure where in the UI these would show if they even were populated, but I will continue to return this data in case it becomes useful..</param>
        /// <param name="InsertAction">Defines what happens when a plug is inserted into sockets of this type..</param>
        /// <param name="PlugWhitelist">A list of Plug \&quot;Categories\&quot; that are allowed to be plugged into sockets of this type.  These should be compared against a given plug item&#39;s DestinyInventoryItemDefinition.plug.plugCategoryHash, which indicates the plug item&#39;s category.  If the plug&#39;s category matches any whitelisted plug, or if the whitelist is empty, it is allowed to be inserted..</param>
        /// <param name="SocketCategoryHash">SocketCategoryHash.</param>
        /// <param name="Visibility">Sometimes a socket isn&#39;t visible. These are some of the conditions under which sockets of this type are not visible. Unfortunately, the truth of visibility is much, much more complex. Best to rely on the live data for whether the socket is visible and enabled..</param>
        /// <param name="AlwaysRandomizeSockets">AlwaysRandomizeSockets.</param>
        /// <param name="IsPreviewEnabled">IsPreviewEnabled.</param>
        /// <param name="HideDuplicateReusablePlugs">HideDuplicateReusablePlugs.</param>
        /// <param name="OverridesUiAppearance">This property indicates if the socket type determines whether Emblem icons and nameplates should be overridden by the inserted plug item&#39;s icon and nameplate..</param>
        /// <param name="AvoidDuplicatesOnInitialization">AvoidDuplicatesOnInitialization.</param>
        /// <param name="CurrencyScalars">CurrencyScalars.</param>
        /// <param name="Hash">The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to..</param>
        /// <param name="Index">The index of the entity as it was found in the investment tables..</param>
        /// <param name="Redacted">If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!.</param>
        public DestinyDefinitionsSocketsDestinySocketTypeDefinition(DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition DisplayProperties = default(DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition), DestinyDefinitionsSocketsDestinyInsertPlugActionDefinition InsertAction = default(DestinyDefinitionsSocketsDestinyInsertPlugActionDefinition), List<DestinyDefinitionsSocketsDestinyPlugWhitelistEntryDefinition> PlugWhitelist = default(List<DestinyDefinitionsSocketsDestinyPlugWhitelistEntryDefinition>), uint? SocketCategoryHash = default(uint?), DestinyDestinySocketVisibility Visibility = default(DestinyDestinySocketVisibility), bool? AlwaysRandomizeSockets = default(bool?), bool? IsPreviewEnabled = default(bool?), bool? HideDuplicateReusablePlugs = default(bool?), bool? OverridesUiAppearance = default(bool?), bool? AvoidDuplicatesOnInitialization = default(bool?), List<DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry> CurrencyScalars = default(List<DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry>), uint? Hash = default(uint?), int? Index = default(int?), bool? Redacted = default(bool?))
        {
            this.DisplayProperties = DisplayProperties;
            this.InsertAction = InsertAction;
            this.PlugWhitelist = PlugWhitelist;
            this.SocketCategoryHash = SocketCategoryHash;
            this.Visibility = Visibility;
            this.AlwaysRandomizeSockets = AlwaysRandomizeSockets;
            this.IsPreviewEnabled = IsPreviewEnabled;
            this.HideDuplicateReusablePlugs = HideDuplicateReusablePlugs;
            this.OverridesUiAppearance = OverridesUiAppearance;
            this.AvoidDuplicatesOnInitialization = AvoidDuplicatesOnInitialization;
            this.CurrencyScalars = CurrencyScalars;
            this.Hash = Hash;
            this.Index = Index;
            this.Redacted = Redacted;
        }
        
        /// <summary>
        /// There are fields for this display data, but they appear to be unpopulated as of now. I am not sure where in the UI these would show if they even were populated, but I will continue to return this data in case it becomes useful.
        /// </summary>
        /// <value>There are fields for this display data, but they appear to be unpopulated as of now. I am not sure where in the UI these would show if they even were populated, but I will continue to return this data in case it becomes useful.</value>
        [DataMember(Name="displayProperties", EmitDefaultValue=false)]
        public DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition DisplayProperties { get; set; }

        /// <summary>
        /// Defines what happens when a plug is inserted into sockets of this type.
        /// </summary>
        /// <value>Defines what happens when a plug is inserted into sockets of this type.</value>
        [DataMember(Name="insertAction", EmitDefaultValue=false)]
        public DestinyDefinitionsSocketsDestinyInsertPlugActionDefinition InsertAction { get; set; }

        /// <summary>
        /// A list of Plug \&quot;Categories\&quot; that are allowed to be plugged into sockets of this type.  These should be compared against a given plug item&#39;s DestinyInventoryItemDefinition.plug.plugCategoryHash, which indicates the plug item&#39;s category.  If the plug&#39;s category matches any whitelisted plug, or if the whitelist is empty, it is allowed to be inserted.
        /// </summary>
        /// <value>A list of Plug \&quot;Categories\&quot; that are allowed to be plugged into sockets of this type.  These should be compared against a given plug item&#39;s DestinyInventoryItemDefinition.plug.plugCategoryHash, which indicates the plug item&#39;s category.  If the plug&#39;s category matches any whitelisted plug, or if the whitelist is empty, it is allowed to be inserted.</value>
        [DataMember(Name="plugWhitelist", EmitDefaultValue=false)]
        public List<DestinyDefinitionsSocketsDestinyPlugWhitelistEntryDefinition> PlugWhitelist { get; set; }

        /// <summary>
        /// Gets or Sets SocketCategoryHash
        /// </summary>
        [DataMember(Name="socketCategoryHash", EmitDefaultValue=false)]
        public uint? SocketCategoryHash { get; set; }

        /// <summary>
        /// Sometimes a socket isn&#39;t visible. These are some of the conditions under which sockets of this type are not visible. Unfortunately, the truth of visibility is much, much more complex. Best to rely on the live data for whether the socket is visible and enabled.
        /// </summary>
        /// <value>Sometimes a socket isn&#39;t visible. These are some of the conditions under which sockets of this type are not visible. Unfortunately, the truth of visibility is much, much more complex. Best to rely on the live data for whether the socket is visible and enabled.</value>
        [DataMember(Name="visibility", EmitDefaultValue=false)]
        public DestinyDestinySocketVisibility Visibility { get; set; }

        /// <summary>
        /// Gets or Sets AlwaysRandomizeSockets
        /// </summary>
        [DataMember(Name="alwaysRandomizeSockets", EmitDefaultValue=false)]
        public bool? AlwaysRandomizeSockets { get; set; }

        /// <summary>
        /// Gets or Sets IsPreviewEnabled
        /// </summary>
        [DataMember(Name="isPreviewEnabled", EmitDefaultValue=false)]
        public bool? IsPreviewEnabled { get; set; }

        /// <summary>
        /// Gets or Sets HideDuplicateReusablePlugs
        /// </summary>
        [DataMember(Name="hideDuplicateReusablePlugs", EmitDefaultValue=false)]
        public bool? HideDuplicateReusablePlugs { get; set; }

        /// <summary>
        /// This property indicates if the socket type determines whether Emblem icons and nameplates should be overridden by the inserted plug item&#39;s icon and nameplate.
        /// </summary>
        /// <value>This property indicates if the socket type determines whether Emblem icons and nameplates should be overridden by the inserted plug item&#39;s icon and nameplate.</value>
        [DataMember(Name="overridesUiAppearance", EmitDefaultValue=false)]
        public bool? OverridesUiAppearance { get; set; }

        /// <summary>
        /// Gets or Sets AvoidDuplicatesOnInitialization
        /// </summary>
        [DataMember(Name="avoidDuplicatesOnInitialization", EmitDefaultValue=false)]
        public bool? AvoidDuplicatesOnInitialization { get; set; }

        /// <summary>
        /// Gets or Sets CurrencyScalars
        /// </summary>
        [DataMember(Name="currencyScalars", EmitDefaultValue=false)]
        public List<DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry> CurrencyScalars { get; set; }

        /// <summary>
        /// The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to.
        /// </summary>
        /// <value>The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to.</value>
        [DataMember(Name="hash", EmitDefaultValue=false)]
        public uint? Hash { get; set; }

        /// <summary>
        /// The index of the entity as it was found in the investment tables.
        /// </summary>
        /// <value>The index of the entity as it was found in the investment tables.</value>
        [DataMember(Name="index", EmitDefaultValue=false)]
        public int? Index { get; set; }

        /// <summary>
        /// If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
        /// </summary>
        /// <value>If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!</value>
        [DataMember(Name="redacted", EmitDefaultValue=false)]
        public bool? Redacted { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DestinyDefinitionsSocketsDestinySocketTypeDefinition {\n");
            sb.Append("  DisplayProperties: ").Append(DisplayProperties).Append("\n");
            sb.Append("  InsertAction: ").Append(InsertAction).Append("\n");
            sb.Append("  PlugWhitelist: ").Append(PlugWhitelist).Append("\n");
            sb.Append("  SocketCategoryHash: ").Append(SocketCategoryHash).Append("\n");
            sb.Append("  Visibility: ").Append(Visibility).Append("\n");
            sb.Append("  AlwaysRandomizeSockets: ").Append(AlwaysRandomizeSockets).Append("\n");
            sb.Append("  IsPreviewEnabled: ").Append(IsPreviewEnabled).Append("\n");
            sb.Append("  HideDuplicateReusablePlugs: ").Append(HideDuplicateReusablePlugs).Append("\n");
            sb.Append("  OverridesUiAppearance: ").Append(OverridesUiAppearance).Append("\n");
            sb.Append("  AvoidDuplicatesOnInitialization: ").Append(AvoidDuplicatesOnInitialization).Append("\n");
            sb.Append("  CurrencyScalars: ").Append(CurrencyScalars).Append("\n");
            sb.Append("  Hash: ").Append(Hash).Append("\n");
            sb.Append("  Index: ").Append(Index).Append("\n");
            sb.Append("  Redacted: ").Append(Redacted).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DestinyDefinitionsSocketsDestinySocketTypeDefinition);
        }

        /// <summary>
        /// Returns true if DestinyDefinitionsSocketsDestinySocketTypeDefinition instances are equal
        /// </summary>
        /// <param name="input">Instance of DestinyDefinitionsSocketsDestinySocketTypeDefinition to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DestinyDefinitionsSocketsDestinySocketTypeDefinition input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DisplayProperties == input.DisplayProperties ||
                    (this.DisplayProperties != null &&
                    this.DisplayProperties.Equals(input.DisplayProperties))
                ) && 
                (
                    this.InsertAction == input.InsertAction ||
                    (this.InsertAction != null &&
                    this.InsertAction.Equals(input.InsertAction))
                ) && 
                (
                    this.PlugWhitelist == input.PlugWhitelist ||
                    this.PlugWhitelist != null &&
                    this.PlugWhitelist.SequenceEqual(input.PlugWhitelist)
                ) && 
                (
                    this.SocketCategoryHash == input.SocketCategoryHash ||
                    (this.SocketCategoryHash != null &&
                    this.SocketCategoryHash.Equals(input.SocketCategoryHash))
                ) && 
                (
                    this.Visibility == input.Visibility ||
                    (this.Visibility != null &&
                    this.Visibility.Equals(input.Visibility))
                ) && 
                (
                    this.AlwaysRandomizeSockets == input.AlwaysRandomizeSockets ||
                    (this.AlwaysRandomizeSockets != null &&
                    this.AlwaysRandomizeSockets.Equals(input.AlwaysRandomizeSockets))
                ) && 
                (
                    this.IsPreviewEnabled == input.IsPreviewEnabled ||
                    (this.IsPreviewEnabled != null &&
                    this.IsPreviewEnabled.Equals(input.IsPreviewEnabled))
                ) && 
                (
                    this.HideDuplicateReusablePlugs == input.HideDuplicateReusablePlugs ||
                    (this.HideDuplicateReusablePlugs != null &&
                    this.HideDuplicateReusablePlugs.Equals(input.HideDuplicateReusablePlugs))
                ) && 
                (
                    this.OverridesUiAppearance == input.OverridesUiAppearance ||
                    (this.OverridesUiAppearance != null &&
                    this.OverridesUiAppearance.Equals(input.OverridesUiAppearance))
                ) && 
                (
                    this.AvoidDuplicatesOnInitialization == input.AvoidDuplicatesOnInitialization ||
                    (this.AvoidDuplicatesOnInitialization != null &&
                    this.AvoidDuplicatesOnInitialization.Equals(input.AvoidDuplicatesOnInitialization))
                ) && 
                (
                    this.CurrencyScalars == input.CurrencyScalars ||
                    this.CurrencyScalars != null &&
                    this.CurrencyScalars.SequenceEqual(input.CurrencyScalars)
                ) && 
                (
                    this.Hash == input.Hash ||
                    (this.Hash != null &&
                    this.Hash.Equals(input.Hash))
                ) && 
                (
                    this.Index == input.Index ||
                    (this.Index != null &&
                    this.Index.Equals(input.Index))
                ) && 
                (
                    this.Redacted == input.Redacted ||
                    (this.Redacted != null &&
                    this.Redacted.Equals(input.Redacted))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DisplayProperties != null)
                    hashCode = hashCode * 59 + this.DisplayProperties.GetHashCode();
                if (this.InsertAction != null)
                    hashCode = hashCode * 59 + this.InsertAction.GetHashCode();
                if (this.PlugWhitelist != null)
                    hashCode = hashCode * 59 + this.PlugWhitelist.GetHashCode();
                if (this.SocketCategoryHash != null)
                    hashCode = hashCode * 59 + this.SocketCategoryHash.GetHashCode();
                if (this.Visibility != null)
                    hashCode = hashCode * 59 + this.Visibility.GetHashCode();
                if (this.AlwaysRandomizeSockets != null)
                    hashCode = hashCode * 59 + this.AlwaysRandomizeSockets.GetHashCode();
                if (this.IsPreviewEnabled != null)
                    hashCode = hashCode * 59 + this.IsPreviewEnabled.GetHashCode();
                if (this.HideDuplicateReusablePlugs != null)
                    hashCode = hashCode * 59 + this.HideDuplicateReusablePlugs.GetHashCode();
                if (this.OverridesUiAppearance != null)
                    hashCode = hashCode * 59 + this.OverridesUiAppearance.GetHashCode();
                if (this.AvoidDuplicatesOnInitialization != null)
                    hashCode = hashCode * 59 + this.AvoidDuplicatesOnInitialization.GetHashCode();
                if (this.CurrencyScalars != null)
                    hashCode = hashCode * 59 + this.CurrencyScalars.GetHashCode();
                if (this.Hash != null)
                    hashCode = hashCode * 59 + this.Hash.GetHashCode();
                if (this.Index != null)
                    hashCode = hashCode * 59 + this.Index.GetHashCode();
                if (this.Redacted != null)
                    hashCode = hashCode * 59 + this.Redacted.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
