/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = BungieAPI.Client.SwaggerDateConverter;

namespace BungieAPI.Model
{
    /// <summary>
    /// DestinyDefinitionsDestinyVendorGroupReference
    /// </summary>
    [DataContract]
    public partial class DestinyDefinitionsDestinyVendorGroupReference :  IEquatable<DestinyDefinitionsDestinyVendorGroupReference>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DestinyDefinitionsDestinyVendorGroupReference" /> class.
        /// </summary>
        /// <param name="vendorGroupHash">The DestinyVendorGroupDefinition to which this Vendor can belong..</param>
        public DestinyDefinitionsDestinyVendorGroupReference(int? vendorGroupHash = default(int?))
        {
            this.VendorGroupHash = vendorGroupHash;
        }
        
        /// <summary>
        /// The DestinyVendorGroupDefinition to which this Vendor can belong.
        /// </summary>
        /// <value>The DestinyVendorGroupDefinition to which this Vendor can belong.</value>
        [DataMember(Name="vendorGroupHash", EmitDefaultValue=false)]
        public int? VendorGroupHash { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DestinyDefinitionsDestinyVendorGroupReference {\n");
            sb.Append("  VendorGroupHash: ").Append(VendorGroupHash).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DestinyDefinitionsDestinyVendorGroupReference);
        }

        /// <summary>
        /// Returns true if DestinyDefinitionsDestinyVendorGroupReference instances are equal
        /// </summary>
        /// <param name="input">Instance of DestinyDefinitionsDestinyVendorGroupReference to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DestinyDefinitionsDestinyVendorGroupReference input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.VendorGroupHash == input.VendorGroupHash ||
                    (this.VendorGroupHash != null &&
                    this.VendorGroupHash.Equals(input.VendorGroupHash))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.VendorGroupHash != null)
                    hashCode = hashCode * 59 + this.VendorGroupHash.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
