/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = BungieAPI.Client.SwaggerDateConverter;

namespace BungieAPI.Model
{
    /// <summary>
    /// DestinyComponentsRecordsDestinyCharacterRecordsComponent
    /// </summary>
    [DataContract]
    public partial class DestinyComponentsRecordsDestinyCharacterRecordsComponent :  IEquatable<DestinyComponentsRecordsDestinyCharacterRecordsComponent>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DestinyComponentsRecordsDestinyCharacterRecordsComponent" /> class.
        /// </summary>
        /// <param name="featuredRecordHashes">featuredRecordHashes.</param>
        /// <param name="records">records.</param>
        public DestinyComponentsRecordsDestinyCharacterRecordsComponent(List<int?> featuredRecordHashes = default(List<int?>), Dictionary<string, DestinyComponentsRecordsDestinyRecordComponent> records = default(Dictionary<string, DestinyComponentsRecordsDestinyRecordComponent>))
        {
            this.FeaturedRecordHashes = featuredRecordHashes;
            this.Records = records;
        }
        
        /// <summary>
        /// Gets or Sets FeaturedRecordHashes
        /// </summary>
        [DataMember(Name="featuredRecordHashes", EmitDefaultValue=false)]
        public List<int?> FeaturedRecordHashes { get; set; }

        /// <summary>
        /// Gets or Sets Records
        /// </summary>
        [DataMember(Name="records", EmitDefaultValue=false)]
        public Dictionary<string, DestinyComponentsRecordsDestinyRecordComponent> Records { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DestinyComponentsRecordsDestinyCharacterRecordsComponent {\n");
            sb.Append("  FeaturedRecordHashes: ").Append(FeaturedRecordHashes).Append("\n");
            sb.Append("  Records: ").Append(Records).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DestinyComponentsRecordsDestinyCharacterRecordsComponent);
        }

        /// <summary>
        /// Returns true if DestinyComponentsRecordsDestinyCharacterRecordsComponent instances are equal
        /// </summary>
        /// <param name="input">Instance of DestinyComponentsRecordsDestinyCharacterRecordsComponent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DestinyComponentsRecordsDestinyCharacterRecordsComponent input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FeaturedRecordHashes == input.FeaturedRecordHashes ||
                    this.FeaturedRecordHashes != null &&
                    this.FeaturedRecordHashes.SequenceEqual(input.FeaturedRecordHashes)
                ) && 
                (
                    this.Records == input.Records ||
                    this.Records != null &&
                    this.Records.SequenceEqual(input.Records)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FeaturedRecordHashes != null)
                    hashCode = hashCode * 59 + this.FeaturedRecordHashes.GetHashCode();
                if (this.Records != null)
                    hashCode = hashCode * 59 + this.Records.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
