/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserUserInfoCard } from './userUserInfoCard';


export interface CommunityCommunityLiveStatus { 
    dateStatusUpdated?: Date;
    url?: string;
    partnershipIdentifier?: string;
    partnershipType?: number;
    thumbnail?: string;
    thumbnailSmall?: string;
    thumbnailLarge?: string;
    destinyCharacterId?: number;
    userInfo?: UserUserInfoCard;
    currentActivityHash?: number;
    dateLastPlayed?: Date;
    dateStreamStarted?: Date;
    locale?: string;
    currentViewers?: number;
    followers?: number;
    overallViewers?: number;
    isFeatured?: boolean;
    title?: string;
    activityModeHash?: number;
    dateFeatured?: Date;
    trendingValue?: number;
    isSubscribable?: boolean;
}

