/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances = 0 | 1 | 2 | 4 | 8 | 16 | 32 | 64 | 128 | 256 | 512 | 1024 | 2048 | 4096 | 8191;

export const DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances = {
    NUMBER_0: 0 as DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances,
    NUMBER_1: 1 as DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances,
    NUMBER_2: 2 as DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances,
    NUMBER_4: 4 as DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances,
    NUMBER_8: 8 as DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances,
    NUMBER_16: 16 as DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances,
    NUMBER_32: 32 as DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances,
    NUMBER_64: 64 as DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances,
    NUMBER_128: 128 as DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances,
    NUMBER_256: 256 as DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances,
    NUMBER_512: 512 as DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances,
    NUMBER_1024: 1024 as DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances,
    NUMBER_2048: 2048 as DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances,
    NUMBER_4096: 4096 as DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances,
    NUMBER_8191: 8191 as DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances
};
