/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An intrinsic perk on an item, and the requirements for it to be activated.
 */
export interface DestinyDefinitionsDestinyItemPerkEntryDefinition { 
    /**
     * If this perk is not active, this is the string to show for why it's not providing its benefits.
     */
    requirementDisplayString?: string;
    /**
     * A hash identifier for the DestinySandboxPerkDefinition being provided on the item.
     */
    perkHash?: number;
    /**
     * Indicates whether this perk should be shown, or if it should be shown disabled.
     */
    perkVisibility?: number;
}

