/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Display categories can have custom sort orders. These are the possible options.
 */
export type DestinyVendorDisplayCategorySortOrder = 0 | 1;

export const DestinyVendorDisplayCategorySortOrder = {
    NUMBER_0: 0 as DestinyVendorDisplayCategorySortOrder,
    NUMBER_1: 1 as DestinyVendorDisplayCategorySortOrder
};
