/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyEntitiesItemsDestinyItemComponent } from './destinyEntitiesItemsDestinyItemComponent';


export interface DestinyComponentsInventoryDestinyPlatformSilverComponent { 
    /**
     * If a Profile is played on multiple platforms, this is the silver they have for each platform, keyed by Membership Type.
     */
    platformSilver?: { [key: string]: DestinyEntitiesItemsDestinyItemComponent; };
}

