/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The reasons why an item cannot be equipped, if any. Many flags can be set, or \"None\" if
 */
export type DestinyEquipFailureReason = 0 | 1 | 2 | 4 | 8 | 16;

export const DestinyEquipFailureReason = {
    NUMBER_0: 0 as DestinyEquipFailureReason,
    NUMBER_1: 1 as DestinyEquipFailureReason,
    NUMBER_2: 2 as DestinyEquipFailureReason,
    NUMBER_4: 4 as DestinyEquipFailureReason,
    NUMBER_8: 8 as DestinyEquipFailureReason,
    NUMBER_16: 16 as DestinyEquipFailureReason
};
