/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DestinyDefinitionsRecordsDestinyRecordCompletionBlock { 
    /**
     * The number of objectives that must be completed before the objective is considered \"complete\"
     */
    partialCompletionObjectiveCountThreshold?: number;
    scoreValue?: number;
    shouldFireToast?: boolean;
    toastStyle?: number;
}

