/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DestinyBucketCategory = 0 | 1 | 2 | 3 | 4;

export const DestinyBucketCategory = {
    NUMBER_0: 0 as DestinyBucketCategory,
    NUMBER_1: 1 as DestinyBucketCategory,
    NUMBER_2: 2 as DestinyBucketCategory,
    NUMBER_3: 3 as DestinyBucketCategory,
    NUMBER_4: 4 as DestinyBucketCategory
};
