/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyMilestonesDestinyPublicMilestoneActivity } from './destinyMilestonesDestinyPublicMilestoneActivity';
import { DestinyMilestonesDestinyPublicMilestoneChallenge } from './destinyMilestonesDestinyPublicMilestoneChallenge';


export interface DestinyMilestonesDestinyPublicMilestoneQuest { 
    /**
     * Quests are defined as Items in content. As such, this is the hash identifier of the DestinyInventoryItemDefinition that represents this quest. It will have pointers to all of the steps in the quest, and display information for the quest (title, description, icon etc) Individual steps will be referred to in the Quest item's DestinyInventoryItemDefinition.setData property, and themselves are Items with their own renderable data.
     */
    questItemHash?: number;
    /**
     * A milestone need not have an active activity, but if there is one it will be returned here, along with any variant and additional information.
     */
    activity?: DestinyMilestonesDestinyPublicMilestoneActivity;
    /**
     * For the given quest there could be 0-to-Many challenges: mini quests that you can perform in the course of doing this quest, that may grant you rewards and benefits.
     */
    challenges?: Array<DestinyMilestonesDestinyPublicMilestoneChallenge>;
}

