/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A hint for what screen should be shown when this presentation node is clicked into. How you use this is your UI is up to you.
 */
export type DestinyDestinyPresentationScreenStyle = 0 | 1 | 2;

export const DestinyDestinyPresentationScreenStyle = {
    NUMBER_0: 0 as DestinyDestinyPresentationScreenStyle,
    NUMBER_1: 1 as DestinyDestinyPresentationScreenStyle,
    NUMBER_2: 2 as DestinyDestinyPresentationScreenStyle
};
