/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration that indicates the high-level \"type\" of the item, attempting to iron out the context specific differences for specific instances of an entity. For instance, though a weapon may be of various weapon \"Types\", in DestinyItemType they are all classified as \"Weapon\". This allows for better filtering on a higher level of abstraction for the concept of types.   This enum is provided for historical compatibility with Destiny 1, but an ideal alternative is to use DestinyItemCategoryDefinitions and the DestinyItemDefinition.itemCategories property instead. Item Categories allow for arbitrary hierarchies of specificity, and for items to belong to multiple categories across multiple hierarchies simultaneously. For this enum, we pick a single type as a \"best guess\" fit.   NOTE: This is not all of the item types available, and some of these are holdovers from Destiny 1 that may or may not still exist.   I keep updating these because they're so damn convenient. I guess I shouldn't fight it.
 */
export type DestinyDestinyItemType = 0 | 1 | 2 | 3 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29;

export const DestinyDestinyItemType = {
    NUMBER_0: 0 as DestinyDestinyItemType,
    NUMBER_1: 1 as DestinyDestinyItemType,
    NUMBER_2: 2 as DestinyDestinyItemType,
    NUMBER_3: 3 as DestinyDestinyItemType,
    NUMBER_7: 7 as DestinyDestinyItemType,
    NUMBER_8: 8 as DestinyDestinyItemType,
    NUMBER_9: 9 as DestinyDestinyItemType,
    NUMBER_10: 10 as DestinyDestinyItemType,
    NUMBER_11: 11 as DestinyDestinyItemType,
    NUMBER_12: 12 as DestinyDestinyItemType,
    NUMBER_13: 13 as DestinyDestinyItemType,
    NUMBER_14: 14 as DestinyDestinyItemType,
    NUMBER_15: 15 as DestinyDestinyItemType,
    NUMBER_16: 16 as DestinyDestinyItemType,
    NUMBER_17: 17 as DestinyDestinyItemType,
    NUMBER_18: 18 as DestinyDestinyItemType,
    NUMBER_19: 19 as DestinyDestinyItemType,
    NUMBER_20: 20 as DestinyDestinyItemType,
    NUMBER_21: 21 as DestinyDestinyItemType,
    NUMBER_22: 22 as DestinyDestinyItemType,
    NUMBER_23: 23 as DestinyDestinyItemType,
    NUMBER_24: 24 as DestinyDestinyItemType,
    NUMBER_25: 25 as DestinyDestinyItemType,
    NUMBER_26: 26 as DestinyDestinyItemType,
    NUMBER_27: 27 as DestinyDestinyItemType,
    NUMBER_28: 28 as DestinyDestinyItemType,
    NUMBER_29: 29 as DestinyDestinyItemType
};
