/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This appears to be information used when rendering rewards. We don't currently use it on BNet.
 */
export interface DestinyDefinitionsDestinyItemSummaryBlockDefinition { 
    /**
     * Apparently when rendering an item in a reward, this should be used as a sort priority. We're not doing it presently.
     */
    sortPriority?: number;
}

