/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = 0 | 1 | 2 | 4 | 8 | 16 | 32 | 64 | 128 | 255;

export const DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = {
    NUMBER_0: 0 as DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes,
    NUMBER_1: 1 as DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes,
    NUMBER_2: 2 as DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes,
    NUMBER_4: 4 as DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes,
    NUMBER_8: 8 as DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes,
    NUMBER_16: 16 as DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes,
    NUMBER_32: 32 as DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes,
    NUMBER_64: 64 as DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes,
    NUMBER_128: 128 as DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes,
    NUMBER_255: 255 as DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes
};
