/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration representing the potential difficulty levels of an activity. Their names are... more qualitative than quantitative.
 */
export type DestinyDestinyActivityDifficultyTier = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;

export const DestinyDestinyActivityDifficultyTier = {
    NUMBER_0: 0 as DestinyDestinyActivityDifficultyTier,
    NUMBER_1: 1 as DestinyDestinyActivityDifficultyTier,
    NUMBER_2: 2 as DestinyDestinyActivityDifficultyTier,
    NUMBER_3: 3 as DestinyDestinyActivityDifficultyTier,
    NUMBER_4: 4 as DestinyDestinyActivityDifficultyTier,
    NUMBER_5: 5 as DestinyDestinyActivityDifficultyTier,
    NUMBER_6: 6 as DestinyDestinyActivityDifficultyTier,
    NUMBER_7: 7 as DestinyDestinyActivityDifficultyTier
};
