/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information about the category and items currently sold in that category.
 */
export interface DestinyEntitiesVendorsDestinyVendorCategory { 
    /**
     * An index into the DestinyVendorDefinition.displayCategories property, so you can grab the display data for this category.
     */
    displayCategoryIndex?: number;
    /**
     * An ordered list of indexes into items being sold in this category (DestinyVendorDefinition.itemList) which will contain more information about the items being sold themselves. Can also be used to index into DestinyVendorSaleItemComponent data, if you asked for that data to be returned.
     */
    itemIndexes?: Array<number>;
}

