/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of milestone. Milestones can be Tutorials, one-time/triggered/non-repeating but not necessarily tutorials, or Repeating Milestones.
 */
export type DestinyDefinitionsMilestonesDestinyMilestoneType = 0 | 1 | 2 | 3 | 4 | 5;

export const DestinyDefinitionsMilestonesDestinyMilestoneType = {
    NUMBER_0: 0 as DestinyDefinitionsMilestonesDestinyMilestoneType,
    NUMBER_1: 1 as DestinyDefinitionsMilestonesDestinyMilestoneType,
    NUMBER_2: 2 as DestinyDefinitionsMilestonesDestinyMilestoneType,
    NUMBER_3: 3 as DestinyDefinitionsMilestonesDestinyMilestoneType,
    NUMBER_4: 4 as DestinyDefinitionsMilestonesDestinyMilestoneType,
    NUMBER_5: 5 as DestinyDefinitionsMilestonesDestinyMilestoneType
};
