/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DestinyDestinyRecordToastStyle = 0 | 1 | 2 | 3 | 4 | 5;

export const DestinyDestinyRecordToastStyle = {
    NUMBER_0: 0 as DestinyDestinyRecordToastStyle,
    NUMBER_1: 1 as DestinyDestinyRecordToastStyle,
    NUMBER_2: 2 as DestinyDestinyRecordToastStyle,
    NUMBER_3: 3 as DestinyDestinyRecordToastStyle,
    NUMBER_4: 4 as DestinyDestinyRecordToastStyle,
    NUMBER_5: 5 as DestinyDestinyRecordToastStyle
};
