/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15;

export const DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType = {
    NUMBER_0: 0 as DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType,
    NUMBER_1: 1 as DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType,
    NUMBER_2: 2 as DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType,
    NUMBER_3: 3 as DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType,
    NUMBER_4: 4 as DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType,
    NUMBER_5: 5 as DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType,
    NUMBER_6: 6 as DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType,
    NUMBER_7: 7 as DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType,
    NUMBER_8: 8 as DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType,
    NUMBER_9: 9 as DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType,
    NUMBER_10: 10 as DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType,
    NUMBER_11: 11 as DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType,
    NUMBER_12: 12 as DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType,
    NUMBER_13: 13 as DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType,
    NUMBER_14: 14 as DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType,
    NUMBER_15: 15 as DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType
};
