/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ForumsForumPostCategoryEnums = 0 | 1 | 2 | 4 | 8 | 16 | 32 | 64 | 128 | 256 | 512 | 1024;

export const ForumsForumPostCategoryEnums = {
    NUMBER_0: 0 as ForumsForumPostCategoryEnums,
    NUMBER_1: 1 as ForumsForumPostCategoryEnums,
    NUMBER_2: 2 as ForumsForumPostCategoryEnums,
    NUMBER_4: 4 as ForumsForumPostCategoryEnums,
    NUMBER_8: 8 as ForumsForumPostCategoryEnums,
    NUMBER_16: 16 as ForumsForumPostCategoryEnums,
    NUMBER_32: 32 as ForumsForumPostCategoryEnums,
    NUMBER_64: 64 as ForumsForumPostCategoryEnums,
    NUMBER_128: 128 as ForumsForumPostCategoryEnums,
    NUMBER_256: 256 as ForumsForumPostCategoryEnums,
    NUMBER_512: 512 as ForumsForumPostCategoryEnums,
    NUMBER_1024: 1024 as ForumsForumPostCategoryEnums
};
