/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GroupsV2GroupOptionalConversationEditRequest { 
    chatEnabled?: boolean;
    chatName?: string;
    chatSecurity?: GroupsV2GroupOptionalConversationEditRequest.ChatSecurityEnum;
}
export namespace GroupsV2GroupOptionalConversationEditRequest {
    export type ChatSecurityEnum = 0 | 1;
    export const ChatSecurityEnum = {
        NUMBER_0: 0 as ChatSecurityEnum,
        NUMBER_1: 1 as ChatSecurityEnum
    };
}

