/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type GroupsV2Capabilities = 0 | 1 | 2 | 4 | 8 | 16 | 32 | 64;

export const GroupsV2Capabilities = {
    NUMBER_0: 0 as GroupsV2Capabilities,
    NUMBER_1: 1 as GroupsV2Capabilities,
    NUMBER_2: 2 as GroupsV2Capabilities,
    NUMBER_4: 4 as GroupsV2Capabilities,
    NUMBER_8: 8 as GroupsV2Capabilities,
    NUMBER_16: 16 as GroupsV2Capabilities,
    NUMBER_32: 32 as GroupsV2Capabilities,
    NUMBER_64: 64 as GroupsV2Capabilities
};
