/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupsV2GroupUserInfoCard } from './groupsV2GroupUserInfoCard';
import { UserGeneralUser } from './userGeneralUser';


export interface UserUserMembershipData { 
    /**
     * this allows you to see destiny memberships that are visible and linked to this account (regardless of whether or not they have characters on the world server)
     */
    destinyMemberships?: Array<GroupsV2GroupUserInfoCard>;
    bungieNetUser?: UserGeneralUser;
}

